version: "3.8"
services:
  mysql:
    image: mysql:latest
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: "conta"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - kafka-net

  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
    - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 5s
      retries: 10

  zookeeper:
    image: debezium/zookeeper:1.1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - kafka-net

  kafka:
    image: debezium/kafka:1.1
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - kafka-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
networks:
  kafka-net:
    name: kafka-net
    driver: bridge