server:
  port: 8081
spring:
  application:
    name: limite-service
  cache:
    type: redis
  redis:
    host: 192.168.0.108
    port: 6379
  data:
    mongodb:
      host: 192.168.0.108
      port: 27017
  kafka:
    bootstrap-servers: 192.168.0.108:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      missing-topics-fatal: false
      ack-mode: MANUAL_IMMEDIATE
logging:
  level:
    org.springframework.web: DEBUG

app.topic: limite-topic
app.topic.uso: limite-uso
app.topic.taxa: limite-taxa

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true