apiVersion: v1
kind: ConfigMap
metadata:
  name: config-limite
data:
  application.yml: |-
    server:
      port: 8080
    spring:
      application:
        name: limite-service
      main:
        allow-bean-definition-overriding: true
      zipkin:
        base-url: http://192.168.0.113:9411
      cache:
        type: redis
      redis:
        host: redis
        port: 6379
      data:
        mongodb:
          host: mongodb
          port: 27017
      kafka:
        bootstrap-servers: kafka:9092
        consumer:
          group-id: ${spring.application.name}
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          auto-offset-reset: earliest
          enable-auto-commit: true
        listener:
          missing-topics-fatal: false
    logging:
      level:
        org.springframework.web: DEBUG

    app.topic: limite-topic
    app.topic.uso: limite-uso
    app.topic.taxa: limite-taxa
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      metrics:
        export:
          prometheus:
            enabled: true
      endpoint:
        metrics:
          enabled: false
        prometheus:
          enabled: true

