apiVersion: apps/v1
kind: Deployment
metadata:
  name: limite-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: limite
  template:
    metadata:
      labels:
        app: limite
    spec:
      containers:
      - name: limite
        image: fabricio211/limite-service
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 300Mi
            cpu: "100m"
          limits:
            memory: 300Mi
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            scheme: HTTP
            path: /actuator/info
          initialDelaySeconds: 10
          periodSeconds: 40
          timeoutSeconds: 2
          failureThreshold: 30
          successThreshold: 1
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
          - mountPath: /etc/config
            name: config-limite
      volumes:
        - name: config-limite
          configMap:
            name: config-limite
            items:
              - key: application.yaml
                path: application.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: limites
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: limite